/**
 * Project: Fun With Flags
 * Author: Amogh Bihani
 */

var GAME_TYPE_NONE = -1;
var GAME_TYPE_COUNTRY_TO_FLAG = 0;
var GAME_TYPE_FLAG_TO_COUNTRY = 1;
var GAME_TYPE_FLAG_TO_CAPITAL = 2;
var GAME_TYPE_COUNTRY_TO_CAPITAL = 3;

var GAME_MODE_NONE = -1;
var GAME_MODE_ARCADE = 0;
var GAME_MODE_QUIZ = 1;
var GAME_MODE_TIME_TRIAL = 2;
var GAME_MODE_INFINITE = 3;

var NUM_QUESTIONS_IN_QUIZ = 10;
var NUM_OPTIONS = 4;
var NUM_DO_NOT_REPEAT_TILL = 50;
var NUM_SECONDS_TIME_TRIAL = 60;
