/**
 * Project: Fun With Flags
 * Author: Amogh Bihani
 */

var countryData = [
    {source:"data/flags/af.png", name:"Afghanistan", capital:"Kabul"},
    {source:"data/flags/al.png", name:"Albania", capital:"Tirana"},
    {source:"data/flags/dz.png", name:"Algeria", capital:"Algiers"},
    {source:"data/flags/ad.png", name:"Andorra", capital:"Andorra la Vella"},
    {source:"data/flags/ao.png", name:"Angola", capital:"Luanda"},
    {source:"data/flags/ag.png", name:"Antigua and Barbuda", capital:"St. John's"},
    {source:"data/flags/ar.png", name:"Argentina", capital:"Buenos Aires"},
    {source:"data/flags/am.png", name:"Armenia", capital:"Yerevan"},
    {source:"data/flags/au.png", name:"Australia", capital:"Canberra"},
    {source:"data/flags/at.png", name:"Austria", capital:"Vienna"},
    {source:"data/flags/az.png", name:"Azerbaijan", capital:"Baku"},
    {source:"data/flags/bs.png", name:"The Bahamas", capital:"Nassau"},
    {source:"data/flags/bh.png", name:"Bahrain", capital:"Manama"},
    {source:"data/flags/bd.png", name:"Bangladesh", capital:"Dhaka"},
    {source:"data/flags/bb.png", name:"Barbados", capital:"Bridgetown"},
    {source:"data/flags/by.png", name:"Belarus", capital:"Minsk"},
    {source:"data/flags/be.png", name:"Belgium", capital:"Brussels"},
    {source:"data/flags/bz.png", name:"Belize", capital:"Belmopan"},
    {source:"data/flags/bj.png", name:"Benin", capital:"Porto-Novo"},
    {source:"data/flags/bt.png", name:"Bhutan", capital:"Thimphu"},
    {source:"data/flags/bo.png", name:"Bolivia", capital:"Sucre"},
    {source:"data/flags/ba.png", name:"Bosnia and Herzegovina", capital:"Sarajevo"},
    {source:"data/flags/bw.png", name:"Botswana", capital:"Gaborone"},
    {source:"data/flags/br.png", name:"Brazil", capital:"Brasília"},
    {source:"data/flags/bn.png", name:"Brunei", capital:"Bandar Seri Begawan"},
    {source:"data/flags/bg.png", name:"Bulgaria", capital:"Sofia"},
    {source:"data/flags/bf.png", name:"Burkina Faso", capital:"Ouagadougou"},
    {source:"data/flags/bi.png", name:"Burundi", capital:"Bujumbura"},
    {source:"data/flags/kh.png", name:"Cambodia", capital:"Phnom Penh"},
    {source:"data/flags/cm.png", name:"Cameroon", capital:"Yaoundé"},
    {source:"data/flags/ca.png", name:"Canada", capital:"Ottawa"},
    {source:"data/flags/cv.png", name:"Cape Verde", capital:"Praia"},
    {source:"data/flags/cf.png", name:"The Central African Republic", capital:"Bangui"},
    {source:"data/flags/td.png", name:"Chad", capital:"N'Djamena"},
    {source:"data/flags/cl.png", name:"Chile", capital:"Santiago"},
    {source:"data/flags/co.png", name:"Colombia", capital:"Bogotá"},
    {source:"data/flags/km.png", name:"The Comoros", capital:"Moroni"},
    {source:"data/flags/cr.png", name:"Costa Rica", capital:"San José"},
    {source:"data/flags/ci.png", name:"Cote d'Ivoire", capital:"Yamoussoukro"},
    {source:"data/flags/hr.png", name:"Croatia", capital:"Zagreb"},
    {source:"data/flags/cu.png", name:"Cuba", capital:"Havana"},
    {source:"data/flags/cy.png", name:"Cyprus", capital:"Nicosia"},
    {source:"data/flags/cz.png", name:"The Czech Republic", capital:"Prague"},
    {source:"data/flags/cd.png", name:"The Democratic Republic of the Congo", capital:"Kinshasa"},
    {source:"data/flags/dk.png", name:"Denmark", capital:"Copenhagen"},
    {source:"data/flags/dj.png", name:"Djibouti", capital:"Djibouti"},
    {source:"data/flags/dm.png", name:"Dominica", capital:"Roseau"},
    {source:"data/flags/do.png", name:"The Dominican Republic", capital:"Santo Domingo"},
    {source:"data/flags/tl.png", name:"East Timor", capital:"Dili"},
    {source:"data/flags/ec.png", name:"Ecuador", capital:"Quito"},
    {source:"data/flags/eg.png", name:"Egypt", capital:"Cairo"},
    {source:"data/flags/sv.png", name:"El Salvador", capital:"San Salvador"},
    {source:"data/flags/gq.png", name:"Equatorial Guinea", capital:"Malabo"},
    {source:"data/flags/er.png", name:"Eritrea", capital:"Asmara"},
    {source:"data/flags/ee.png", name:"Estonia", capital:"Tallinn"},
    {source:"data/flags/et.png", name:"Ethiopia", capital:"Addis Ababa"},
    {source:"data/flags/fj.png", name:"Fiji", capital:"Suva"},
    {source:"data/flags/fi.png", name:"Finland", capital:"Helsinki"},
    {source:"data/flags/fr.png", name:"France", capital:"Paris"},
    {source:"data/flags/ga.png", name:"Gabon", capital:"Libreville"},
    {source:"data/flags/gm.png", name:"The Gambia", capital:"Banjul"},
    {source:"data/flags/ge.png", name:"Georgia", capital:"Tbilisi"},
    {source:"data/flags/de.png", name:"Germany", capital:"Berlin"},
    {source:"data/flags/gh.png", name:"Ghana", capital:"Accra"},
    {source:"data/flags/gr.png", name:"Greece", capital:"Athens"},
    {source:"data/flags/gd.png", name:"Grenada", capital:"St. George's"},
    {source:"data/flags/gt.png", name:"Guatemala", capital:"Guatemala City"},
    {source:"data/flags/gn.png", name:"Guinea", capital:"Conakry"},
    {source:"data/flags/gw.png", name:"Guinea-Bissau", capital:"Bissau"},
    {source:"data/flags/gy.png", name:"Guyana", capital:"Georgetown"},
    {source:"data/flags/ht.png", name:"Haiti", capital:"Port-au-Prince"},
    {source:"data/flags/hn.png", name:"Honduras", capital:"Tegucigalpa"},
    {source:"data/flags/hu.png", name:"Hungary", capital:"Budapest"},
    {source:"data/flags/is.png", name:"Iceland", capital:"Reykjavík"},
    {source:"data/flags/in.png", name:"India", capital:"New Delhi"},
    {source:"data/flags/id.png", name:"Indonesia", capital:"Jakarta"},
    {source:"data/flags/ir.png", name:"Iran", capital:"Tehran"},
    {source:"data/flags/iq.png", name:"Iraq", capital:"Baghdad"},
    {source:"data/flags/ie.png", name:"Ireland", capital:"Dublin"},
    {source:"data/flags/il.png", name:"Israel", capital:"Jerusalem"},
    {source:"data/flags/it.png", name:"Italy", capital:"Rome"},
    {source:"data/flags/jm.png", name:"Jamaica", capital:"Kingston"},
    {source:"data/flags/jp.png", name:"Japan", capital:"Tokyo"},
    {source:"data/flags/jo.png", name:"Jordan", capital:"Amman"},
    {source:"data/flags/kz.png", name:"Kazakhstan", capital:"Astana"},
    {source:"data/flags/ke.png", name:"Kenya", capital:"Nairobi"},
    {source:"data/flags/ki.png", name:"Kiribati", capital:"South Tarawa"},
    {source:"data/flags/ks.png", name:"Kosovo", capital:"Pristina"},
    {source:"data/flags/kw.png", name:"Kuwait", capital:"Kuwait City"},
    {source:"data/flags/kg.png", name:"Kyrgyzstan", capital:"Bishkek"},
    {source:"data/flags/la.png", name:"Laos", capital:"Vientiane"},
    {source:"data/flags/lv.png", name:"Latvia", capital:"Riga"},
    {source:"data/flags/lb.png", name:"Lebanon", capital:"Beirut"},
    {source:"data/flags/ls.png", name:"Lesotho", capital:"Maseru"},
    {source:"data/flags/lr.png", name:"Liberia", capital:"Monrovia"},
    {source:"data/flags/ly.png", name:"Libya", capital:"Tripoli"},
    {source:"data/flags/li.png", name:"Liechtenstein", capital:"Vaduz"},
    {source:"data/flags/lt.png", name:"Lithuania", capital:"Vilnius"},
    {source:"data/flags/lu.png", name:"Luxembourg", capital:"Luxembourg City"},
    {source:"data/flags/mk.png", name:"Macedonia", capital:"Skopje"},
    {source:"data/flags/mg.png", name:"Madagascar", capital:"Antananarivo"},
    {source:"data/flags/mw.png", name:"Malawi", capital:"Lilongwe"},
    {source:"data/flags/my.png", name:"Malaysia", capital:"Kuala Lumpur"},
    {source:"data/flags/mv.png", name:"Maldives", capital:"Malé"},
    {source:"data/flags/ml.png", name:"Mali", capital:"Bamako"},
    {source:"data/flags/mt.png", name:"Malta", capital:"Valletta"},
    {source:"data/flags/mh.png", name:"The Marshall Islands", capital:"Majuro"},
    {source:"data/flags/mr.png", name:"Mauritania", capital:"Nouakchott"},
    {source:"data/flags/mu.png", name:"Mauritius", capital:"Port Louis"},
    {source:"data/flags/mx.png", name:"Mexico", capital:"Mexico City"},
    {source:"data/flags/fm.png", name:"Micronesia", capital:"Palikir"},
    {source:"data/flags/md.png", name:"Moldova", capital:"Chisinau"},
    {source:"data/flags/mc.png", name:"Monaco", capital:"Monaco"},
    {source:"data/flags/mn.png", name:"Mongolia", capital:"Ulaanbaatar"},
    {source:"data/flags/me.png", name:"Montenegro", capital:"Podgorica"},
    {source:"data/flags/ma.png", name:"Morocco", capital:"Rabat"},
    {source:"data/flags/mz.png", name:"Mozambique", capital:"Maputo"},
    {source:"data/flags/mm.png", name:"Myanmar", capital:"Naypyidaw"},
    {source:"data/flags/na.png", name:"Namibia", capital:"Windhoek"},
    {source:"data/flags/nr.png", name:"Nauru", capital:"Yaren District"},
    {source:"data/flags/np.png", name:"Nepal", capital:"Kathmandu"},
    {source:"data/flags/nl.png", name:"The Netherlands", capital:"Amsterdam"},
    {source:"data/flags/nz.png", name:"New Zealand", capital:"Wellington"},
    {source:"data/flags/ni.png", name:"Nicaragua", capital:"Managua"},
    {source:"data/flags/ne.png", name:"Niger", capital:"Niamey"},
    {source:"data/flags/ng.png", name:"Nigeria", capital:"Abuja"},
    {source:"data/flags/kp.png", name:"North Korea", capital:"Pyongyang"},
    {source:"data/flags/no.png", name:"Norway", capital:"Oslo"},
    {source:"data/flags/om.png", name:"Oman", capital:"Muscat"},
    {source:"data/flags/pk.png", name:"Pakistan", capital:"Islamabad"},
    {source:"data/flags/pw.png", name:"Palau", capital:"Ngerulmud"},
    {source:"data/flags/pa.png", name:"Panama", capital:"Panama City"},
    {source:"data/flags/pg.png", name:"Papua New Guinea", capital:"Port Moresby"},
    {source:"data/flags/py.png", name:"Paraguay", capital:"Asunción"},
    {source:"data/flags/cn.png", name:"The People's Republic of China", capital:"Beijing"},
    {source:"data/flags/pe.png", name:"Peru", capital:"Lima"},
    {source:"data/flags/ph.png", name:"The Philippines", capital:"Manila"},
    {source:"data/flags/pl.png", name:"Poland", capital:"Warsaw"},
    {source:"data/flags/pt.png", name:"Portugal", capital:"Lisbon"},
    {source:"data/flags/qa.png", name:"Qatar", capital:"Doha"},
    {source:"data/flags/tw.png", name:"The Republic of China", capital:"Taipei"},
    {source:"data/flags/cg.png", name:"The Republic of the Congo", capital:"Brazzaville"},
    {source:"data/flags/ro.png", name:"Romania", capital:"Bucharest"},
    {source:"data/flags/ru.png", name:"Russia", capital:"Moscow"},
    {source:"data/flags/rw.png", name:"Rwanda", capital:"Kigali"},
    {source:"data/flags/kn.png", name:"Saint Kitts and Nevis", capital:"Basseterre"},
    {source:"data/flags/lc.png", name:"Saint Lucia", capital:"Castries"},
    {source:"data/flags/vc.png", name:"Saint Vincent and the Grenadines", capital:"Kingstown"},
    {source:"data/flags/ws.png", name:"Samoa", capital:"Apia"},
    {source:"data/flags/sm.png", name:"San Marino", capital:"San Marino"},
    {source:"data/flags/st.png", name:"Sao Tome and Principe", capital:"São Tomé"},
    {source:"data/flags/sa.png", name:"Saudi Arabia", capital:"Riyadh"},
    {source:"data/flags/sn.png", name:"Senegal", capital:"Dakar"},
    {source:"data/flags/rs.png", name:"Serbia", capital:"Belgrade"},
    {source:"data/flags/sc.png", name:"The Seychelles", capital:"Victoria"},
    {source:"data/flags/sl.png", name:"Sierra Leone", capital:"Freetown"},
    {source:"data/flags/sg.png", name:"Singapore", capital:"Singapore"},
    {source:"data/flags/sk.png", name:"Slovakia", capital:"Bratislava"},
    {source:"data/flags/si.png", name:"Slovenia", capital:"Ljubljana"},
    {source:"data/flags/sb.png", name:"The Solomon Islands", capital:"Honiara"},
    {source:"data/flags/so.png", name:"Somalia", capital:"Mogadishu"},
    {source:"data/flags/za.png", name:"South Africa", capital:"Pretoria"},
    {source:"data/flags/kr.png", name:"South Korea", capital:"Seoul"},
    {source:"data/flags/es.png", name:"Spain", capital:"Madrid"},
    {source:"data/flags/lk.png", name:"Sri Lanka", capital:"Colombo"},
    {source:"data/flags/sd.png", name:"Sudan", capital:"Khartoum"},
    {source:"data/flags/sr.png", name:"Suriname", capital:"Paramaribo"},
    {source:"data/flags/sz.png", name:"Swaziland", capital:"Mbabane"},
    {source:"data/flags/se.png", name:"Sweden", capital:"Stockholm"},
    {source:"data/flags/ch.png", name:"Switzerland", capital:"Bern"},
    {source:"data/flags/sy.png", name:"Syria", capital:"Damascus"},
    {source:"data/flags/tj.png", name:"Tajikistan", capital:"Dushanbe"},
    {source:"data/flags/tz.png", name:"Tanzania", capital:"Dodoma"},
    {source:"data/flags/th.png", name:"Thailand", capital:"Bangkok"},
    {source:"data/flags/tg.png", name:"Togo", capital:"Lomé"},
    {source:"data/flags/to.png", name:"Tonga", capital:"Nuku'alofa"},
    {source:"data/flags/tt.png", name:"Trinidad and Tobago", capital:"Port of Spain"},
    {source:"data/flags/tn.png", name:"Tunisia", capital:"Tunis"},
    {source:"data/flags/tr.png", name:"Turkey", capital:"Ankara"},
    {source:"data/flags/tm.png", name:"Turkmenistan", capital:"Ashgabat"},
    {source:"data/flags/tv.png", name:"Tuvalu", capital:"Funafuti"},
    {source:"data/flags/ug.png", name:"Uganda", capital:"Kampala"},
    {source:"data/flags/ua.png", name:"Ukraine", capital:"Kiev Kyiv"},
    {source:"data/flags/ae.png", name:"The United Arab Emirates", capital:"Abu Dhabi"},
    {source:"data/flags/gb.png", name:"The United Kingdom", capital:"London"},
    {source:"data/flags/us.png", name:"The United States", capital:"Washington, District of Columbia"},
    {source:"data/flags/uy.png", name:"Uruguay", capital:"Montevideo"},
    {source:"data/flags/uz.png", name:"Uzbekistan", capital:"Tashkent"},
    {source:"data/flags/vu.png", name:"Vanuatu", capital:"Port Vila"},
    {source:"data/flags/va.png", name:"The Vatican City", capital:"Vatican City"},
    {source:"data/flags/ve.png", name:"Venezuela", capital:"Caracas"},
    {source:"data/flags/vn.png", name:"Vietnam", capital:"Hanoi"},
    {source:"data/flags/eh.png", name:"Western Sahara", capital:"Laayoune"},
    {source:"data/flags/ye.png", name:"Yemen", capital:"Sanaá"},
    {source:"data/flags/zm.png", name:"Zambia", capital:"Lusaka"},
    {source:"data/flags/zw.png", name:"Zimbabwe", capital:"Harare"}
];
